### ISSUE TITLE
/print not updating data

### ISSUE THREAD

**Issue by NaziYeeter** [AmanoTeam/EduuRobot#328]
tried using it on http://randomcolour.com/
it returns old data not new one.
 
 returning same color when requested twice

**Comment by alissonlauffer** [comment]
Fixed. This API caches screenshots indefinitely, and thus was causing the bot to send the same screenshot.

Apparently it hashes website URL + passed CSS to create unique IDs. There were some solutions, but injecting invalid CSS code seemed the best approach here:

We could add an extra "junk" fragment or parameter, `#like-his` or `?this` at the end of the URL, but that could break when someone wants to screenshot a website that already includes a fragment/breaks when extra parameters are added.

So adding an nonexistent CSS tag seemed the best way to invalidate the screenshot API, while keeping website URL untouched.

**Comment by alissonlauffer** [comment]
@alissonlauffer até que não estou escrevendo ruim em inglês
