### ISSUE TITLE
`/print` command is not working

### ISSUE THREAD

**Issue by ChankitSaini** [AmanoTeam/EduuRobot#378]
just checked that print API is not working, it's returning the following error on telegram.

`API returned an error: Screenshot API returned an invalid response.`

https://github.com/AmanoTeam/EduuRobot/blob/448781ad7083297362456426ac7109a8f5930f1c/eduu/plugins/prints.py#L102

**Comment by ChankitSaini** [comment]
New Screenshot API: https://backup15.terasp.net/

**Comment by alissonlauffer** [comment]
It started to work again.
