### ISSUE TITLE
the weather plugin not working

### ISSUE THREAD

**Issue by iiiiii1wepfj** [AmanoTeam/EduuRobot#80]
the command not working but the code not show any error

**Comment by alissonlauffer** [comment]
It is working fine here. Could you provide more context?

**Comment by iiiiii1wepfj** [comment]
i use the weather command and the bot (my clone and the eduurobot beta not response

**Comment by alissonlauffer** [comment]
Hmmm, that may be some block in weather.com's side. Try running the bot with a different IP and tell me if the issue persists.

**Comment by iiiiii1wepfj** [comment]
ok

**Comment by alissonlauffer** [comment]
I had some issues with weather.com blocking some specific IPs for no reason and solved it by changing User-Agent string. But looks like this issue is still present.

**Comment by iiiiii1wepfj** [comment]
![Screenshot from 2020-10-28 07-12-39](https://user-images.githubusercontent.com/18629298/97395182-07140380-18ed-11eb-81a4-294bd75b0dfd.png)
Thank you

**Comment by alissonlauffer** [comment]
Nice. I will leave this issue open until I find some way to fix this. Maybe using random user-agent strings? As it looks like weather.com blocks requests based in the user-agent (I've changed it to get it working here).

**Comment by iiiiii1wepfj** [comment]
he block my server again

**Comment by alissonlauffer** [comment]
Does this issue still persists?

**Comment by alissonlauffer** [comment]
If yes, can you try changing the User-Agent string in this line:
https://github.com/AmanoTeam/EduuRobot/blob/3f0639e6199d4aad5490b7c494b8291b798c24c8/plugins/weather.py#L14
to:
```text
Mozilla/5.0 (Linux; Android 10; SM-G975U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.93 Mobile Safari/537.36
```

And test if weather.com still blocks your server? My guess is that it should work because the current api key is taken from weather.com's Android app.
